[wokwi]
version=1
firmware='.pio/build/esp32doit-devkit-v1/firmware.bin'
elf='.pio/build/esp32doit-devkit-v1/firmware.elf'

gdbServerPort=3333

# tcp/serial port tcp/4000
rfc2217ServerPort = 4000

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8181"
to = "target:80"

